# this code was generated by Google's Gemini
from datetime import datetime, timedelta

# Define the timeframe
start_date = datetime.strptime("2/26/24", "%m/%d/%y")
end_date = datetime.strptime("4/23/24", "%m/%d/%y")

# Calculate the number of days in the timeframe
num_days = (end_date - start_date).days + 1

# Calculate the average daily purchase frequency
average_purchases_per_day = 1035 / num_days

# Format the average to two decimal places
average_purchases_per_day_formatted = "{:.2f}".format(average_purchases_per_day)

# Choose the most appropriate way to communicate the frequency based on the value
if average_purchases_per_day < 1:
    communication = "Less than 1 purchase per day on average."
elif average_purchases_per_day == 1:
    communication = "An average of 1 purchase per day."
else:
    communication = f"An average of {average_purchases_per_day_formatted} purchases per day."

print(communication)
